### ISSUE TITLE
Milestone 1 Comments

### ISSUE THREAD

**Issue by Glenn032787** [UBC-MDS/horror_movies#11]
Congratulations on finishing milestone 1! We can see you put a lot of work into this project, nice work! Below we list some specific feedback you can use to improve your project.

We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project. If anything is unclear, please feel free to ask questions in this issue thread.

***1. Project set-up (max 20 points)***
- [x] Contributing documentation should reflect all the ways people can contribute to the project 
(core members, who should be working in a GitHub flow workflow involving branching in the main project repo and opening PR's, as well as arms-length contributors, who more likely may have to fork the repo before submitting a PR). **-2**
**Comment:**  Core teams contribution workflow is not mentioned.
- [x]  Creative commons license needs to be included to specify how non-code/software work can be used, shared and derived.
**Comment:** Only included MIT license but missing creative commons license

***2. Project proposal (10 points)***
- [x] The dataset, dataset license and dataset citation should be included in the [README.md](http://readme.md/). -1
**Comment:** Missing dataset license and citation
- [x]  The proposed methodology in the README should be clearly explained, mentioning the statistical methods / models they will use (at least at a high-level). -3 reasoning
**Comment:** What kind of hypothesis test are you going to use? 

- [x] The question should be specific enough. For example, “Is eating a healthier diet better for you?” is written ambiguously. What do you mean by “healthier diet”? . Instead, “Does eating at least 5 servings per day of fresh fruits and vegetables lead to fewer upper respiratory tract infections (colds)?” is clearer and more concrete. -1 reasoning
**Comment:** You have too many research question, you should focus on one specific question. "The primary inferential research question is whether horror movies which are highly rated tend to generate more revenue than those that aren't highly rated." seems more like a causal question rather than and inferential question.  You need to specify what exactly you are comparing in the question (should not include "etc.").

***3. A script that downloads and saves the data***
Great Job!

***4. Exploratory data analysis in a literate code document***
- [x] There are not figure captions. -2 viz
- [x] There figure captions for the tables should be above the table. **-1** **viz**
**Comment:** All figures should have captions below and tables should have captions above. See here for [example](https://clauswilke.com/dataviz/visualizing-amounts.html#tab:boxoffice-gross)

- [x] Missing a summary/abstract in the analysis (.ipynb or .Rmd) file -2
- [x] There is not title, introduction and/or references in the analysis (`.ipynb` or `.Rmd`) file **-2**
**Comment:** Would be good to add introduction in EDA document to explain purpose or goal of the script.

- [x] Narration of methods and method choices was not as clear and thorough as expected. -1
**Comment:** Not very clear why you are showing some of the figures (i.e the Pairs Matrix figure was included with no description). Summary tables are shown without explaining their purpose (ie you can talk about NA values, removing columns such as poster_path)

- [x]  README should include instructions on how to run the analysis. Clearly specify usage instructions to the point a user could copy and paste them and they would work.
**Comment:** You should add example command for downloading data using the down_data.R script with the URL.

- [x]  Dependencies (or link pointing to list elsewhere) is missing from the [README.md](http://readme.md/) file. The dependency list should include docopt package. -2
**Comment:** Missing dependencies 

***Expectations***
- [x] Please provide the link to the release as https://github.com/UBC-MDS/REPOSITORY/tree/VERSION

**Comment by AguilarRaul** [comment]
Hi team, I'm fixing the EDA as per the feedback of milestone 1.  UPDATE: just sent the PR.

**Comment by j99thoms** [comment]
Added dependencies and instructions to the README. 
https://github.com/UBC-MDS/horror_movies/commit/997373e3fb3decf72b0d3cd031f00d0b23911716
https://github.com/UBC-MDS/horror_movies/commit/7b54681c05b95219a207483f949a5e1404a9daad
https://github.com/UBC-MDS/horror_movies/commit/af935b1c930fc36be6ce6794b442d061c88fd2ec

**Comment by Lorraine97** [comment]
Included ways to contribution: 8a4a22131769a1eaa9b08c6ac26abfd788c63fc5
