### ISSUE TITLE
Milestone 2 Grades

### ISSUE THREAD

**Issue by ericlee0920** [UBC-MDS/horror_movies#25]
#### 1.1 Analysis code is abstracted to four (or more) scripts which take command line arguments and save analysis artifacts (e.g., figures and data for tables).

- [x] #30

- [x] Command line arguments are missing from one or more scripts **-3** **accuracy**

- [x] One or more scripts do not save analysis artifacts **-3** **mechanics**

- [ ] One or more documentations could be improved through additional proofreading (i.e., spelling and grammatical errors are present). **-2** **writing**  (Raul)

- [x] Code in one or more scripts is not of high quality, or does not adhere to the adopted code styles for the course: author, date and where the script has been extracted from (if it is a re-used script), should be added **-2**  **quality**

#### 1.2 Report is written in a literate code document, and the code in the literate code document primarily functions to source analysis artifacts and format the document. 

- [x] The `proposal.md` file has been created and moved to the `doc` directory **-2** **mechanics** (Xinru)

- [ ] The literate code document (R Markdown or Jupyter notebook) does not use code to primarily to source analysis artifacts to display and format them (i.e., instead code to generate figures and tables is present in the literate code doc) **-4**  **mechanics** - modify to relative paths (Raul)

- [x] The literate code document (R Markdown or Jupyter notebook) does not hide the code that should be hidden from the reader (all, or almost all, code should be hidden in the final rendered document) **-4** **quality** (Xinru)

- [x] The literate code document (R Markdown or Jupyter notebook) does not use markdown headers to label document sections **-2** **quality** (Raul)

- [ ] The literate code document (R Markdown or Jupyter notebook) does not use code to format table descriptions and figure captions and automatically number them **-4** **quality** (Xinru)

- [ ] The literate code document (R Markdown or Jupyter notebook) does not use markup language syntax correctly to automatically format citations and generate a bibliography **-4** **mechanics** (Xinru)

- [ ] The literate code document (R Markdown) does not use code to automatically update inline values generated from the analysis that are presented in the narrated text of the document **-2** **quality** (Xinru)

- [ ] Plots suffer from one or more severe problems. For instance, overplotting, missing legend, small text or no axis labels. **-5** **viz** (Raul)
  
- [x] There are not figure captions. **-2** **viz** (Raul)

- [x] The report must contain at least 4 citations relevant to the project. **-3** **quality** 

- [ ] The text is unclear and/or has many typos. It is hard to understand the original purpose of the analysis by reading the report.  **-4** **writing** (Xinru)

### 1.3 Code is abstracted to functions with good function design

- [x] There are cases of functions that clearly do more than one thing. **-1** **reasoning** (Raul)

- [] Move violin plot to the EDA **-1** **reasoning** (Jakob)

  
- [ ] There are cases of functions that are too big and could be improved by defining utility functions. **-1** **reasoning**
(Sam)
- [x] There are cases of functions that have very obscure names and/or arguments. **-1** **quality** (Sam)
- [ ] Functions do not follow a consistent style, there are differences among the scripts. **-3** **quality** (Raul)
  
- [x] There are cases of functions that do not check for proper input and/or do not provide useful error messages. **-1** **mechanics**  (Sam)
- [x] There is not at least 1 function per group member. **-3** **mechanics** (Xinru)
   
### 1.4 Functions are well documented

- [ ] Documentation does not follow a consistent style (it is different among files). **-5** **reasoning** (Raul)

- [ ] Moving the violin plot to the EDA . **-5** **reasoning** (Jakob)

- [ ] One or more function documentations are missing **-5** **quality** (Raul)

- [ ] One or more functions are only partially understood from reading their documentation. **-2** **quality** (Sam)
#### 1.5 Code is called in the analysis

- [ ] No defined functions are called in the analysis. **-5** **accuracy** (Xinru)

---

##### From these 7 points remove points if:

- [ ] There are cases of functions with tests that fail. **-3** **accuracy**

- [ ] There is no documentation. It is not clear what the tests are testing. **-3** **quality** 

- [ ] There is commented out code. **-1** **quality** (Sam)

---

#### 1.9 Dependencies have been updated (so it include the test libraries)

- [ ] Dependencies versions are not pinned. **-1** **mechanics**

#### 2.1 GitHub Issues

- [x] GitHub issues were not used. **-2** **mechanics** (Sam)

#### 2.2 Follows GitHub flow version control workflow

- [ ] Project is expected to follow a GitHub flow version control workflow, which requires all branches to have meaningful names to reflect the piece of work being done (not only the names of contributors) and should also include scope (e.g., `feat-draft-analysis` for new feature which is the draft of the analysis, `fix-useage-docs` for some bug fix to the usage documentation) **-1** **mechanics**
- [ ] Project is expected to follow a GitHub flow version control workflow, which requires all branches to be divided into independent units of work (e.g., `feat-draft-analysis` for new feature which is the draft of the analysis, `fix-useage-docs` for some bug fix to the usage documentation) **-1** **mechanics**
- [ ] All contributions are expected to go through pull-request. **-2** **mechanics**
- [ ] Branching in the core team's project repository is the expected workflow, not forking. **-1** **mechanics**
- [ ] All the team-members should have meaninful commits in the project **-5**  **mechanics**

### 3. Project file and directory structure organization

- [ ] Project does not use `src/` for saving files containing user-defined functions. **- 1** **mechanics**
- [ ] There are folder/files that should not be committed. Including a `.gitignore` file is recommended. **- 1** **reasoning** (Raul)

### 3.1 Analysis can be run reproducibly using documentation provided in the README

- [ ] Usage documentation could be improved for clarity (i.e., it is not explicitly clear to the user how to use the project, or some of the wording is confusing). **-5** **writing**

- [ ] Clearly specify usage instructions to the point a user could copy and paste them and they would work. 
If a specific value needs to be inserted suggest the most reasonable value and provide the list 
(or link to a list) of alternative options. **-5** **mechanics**

- [ ] Could not reproducibly run the analysis because a package was missing from the provided computational environment. **-5** **reasoning**

- [ ] Could not reproducibly run the analysis because there are no instructions. **-10** **mechanics**

- [ ] Could not reproducibly run the analysis because the code fails. **-5** **accuracy**

### 4. Submission expectations

- [ ] Please provide the link to the release as `https://github.com/UBC-MDS/REPOSITORY/tree/VERSION` (replacing `REPOSITORY` and `VERSION` with the correct ones for your project version for each milestone). This makes is a lot easier for someone to just visit the repository as it was at that point in the project's history. **-3** **mechanics**
  
- [ ] There is no link nor instructions to access the GitHub release for milestone 2. **-2** **mechanics**

**Comment by Lorraine97** [comment]
- [ ] 1. The proposal.md file has been created and moved to the doc directory -2 mechanics
- [ ] 2. Plots suffer from one or more severe problems. For instance, overplotting, missing legend, small text or no axis labels. -5 viz
- [ ] 3. There are cases of functions with tests that fail. -3 accuracy
- [ ] 4. There is no documentation. It is not clear what the tests are testing. -3 quality


@ericlee0920 originally checked these items. 

@AguilarRaul @Hongjian-Sam-Li @J99thoms
