### ISSUE TITLE
Milestone 3 Grades

### ISSUE THREAD

**Issue by ericlee0920** [UBC-MDS/horror_movies#34]
# Automating the data-analysis pipeline using Make

### A data analysis pipeline written in GNU Make exists, and works to run the analysis from beginning to end, as well as to clean up the analysis

- [ ] The `Makefile` does not have an `all` (or similarly named) phony target that runs the entire analysis **- 5** **accuracy**

- [ ] The `Makefile` does not have an `clean` (or similarly named) phony target that resets the entire analysis to the beginning state **- 5** **accuracy**

- [ ] The `Makefile` does not track all target dependencies, and so some intermediate data files, or analysis artifacts may miss being generated in some cases **- 5**  **accuracy**

- [ ] The `Makefile` is not well documented **- 5** **quality**

- [ ] The `Makefile` is not written in a sensible order, or is disorganized, or difficult to read for some reason **- 5** **accuracy**

- [ ] Target `all` could be simplified by writing something like `all: <report_target>`. **- 2** **mechanics**

### Dependencies have been updated (so it include the test libraries)

- [ ] Dependency versions are not pinned. **- 5** **mechanics**

### Project file and directory structure organization

- [ ] Project does not use `src/` for saving files containing user-defined functions. **- 2** **mechanics**

- [ ] There are folder/files that should not be committed. **- 2** **mechanics**

- [ ] Project does not use `docs/` for saving the report. **- 2** **mechanics**

###  Analysis can be run reproducibly using documentation provided in the README

- [ ] Usage documentation could be improved for clarity (i.e., it is not explicitly clear to the user how to use the project, or some of the wording is confusing). **-2** **quality**

- [ ] Clearly specify usage instructions to the point a user could copy and paste them and they would work. 
If a specific value needs to be inserted (e.g., volume mounting, port forwarding, tag version - which should be specified, as relying on `latest` is unreliable for many reasons, etc) 
suggest the most reasonable value and provide the list 
(or link to a list) of alternative options. **-7** **mechanics**

- [ ] Could not reproducibly run the analysis because a package was missing from the provided computational environment. **-5** **quality**

- [ ] Could not reproducibly run the analysis because there are no instructions. **-5** **quality**

# Expectations

### Follows GitHub flow version control workflow

- [ ] Project is expected to follow a GitHub flow version control workflow, which requires all branches to have meaningful names to reflect the piece of work being done (not names of contributors) and should also include scope (e.g., `feat-draft-analysis` for new feature which is the draft of the analysis, `fix-useage-docs` for some bug fix to the usage documentation) **-2** **mechanics**

- [ ] Project is expected to follow a GitHub flow version control workflow, which requires all branches to be divided into independent units of work (e.g., `feat-draft-analysis` for new feature which is the draft of the analysis, `fix-useage-docs` for some bug fix to the usage documentation) **-2** **mechanics**

- [ ] All contributions are expected to go through code review via a pull-request. **-4** **mechanics**

- [ ] Branching in the core team's project repository is the expected workflow, not forking.  If forking is being done, it is OK, as long as work in the fork is on branches. **-2** **mechanics**

### GitHub release

- [ ] Please provide the link to the release as `https://github.com/UBC-MDS/REPOSITORY/tree/VERSION` (replacing `REPOSITORY` and `VERSION` with the correct ones for your project version for each milestone). This makes is a lot easier for someone to just visit the repository as it was at that point in the project's history. **-2** **mechanics**

- [ ] There is no link nor instructions to access the GitHub release for milestone 2. **-3** **mechanics**

**Comment by Lorraine97** [comment]
@AguilarRaul @Hongjian-Sam-Li @J99thoms it seems that we are good to go here. Closing the issue.
