### ISSUE TITLE
Milestone 4 activities

### ISSUE THREAD

**Issue by AguilarRaul** [UBC-MDS/horror_movies#35]
Hey there,

Based on the Milestone 2 and 3 rubrics, as we mentioned, most of the open points are related to the final report (except some that we already identified e.g. name of the final report).

The idea is to iterate on the final report, once Xinru finishes her part, I will do mine and we will iterate from there. 

Regarding the comment that we have to add to the peer review issue, most of them have to do with the final report and the directory structure so we are safe. I can add the comment with the commit's URL once we are done. 

Notes:

From milestone 2: 

- [x] #39
- [x] #36
- [x] #38
- [x] #37

From milestone 3, we are good!

**Comment by Lorraine97** [comment]
@AguilarRaul I think we should work in parallel! If any conflict is incurred, we should be able to resolve it.

**Comment by AguilarRaul** [comment]
Sure, I agree.

**Comment by Lorraine97** [comment]
From milestone 2: 

- [ ] 1. The proposal.md file has been created and moved to the doc directory -2 mechanics
- [ ] 2. Plots suffer from one or more severe problems. For instance, overplotting, missing legend, small text or no axis labels. -5 viz
- [ ] 3. There are cases of functions with tests that fail. -3 accuracy
- [ ] 4. There is no documentation. It is not clear what the tests are testing. -3 quality

From milestone 3, we are good!

Let's focus on these four items and we should be good to go!

**Comment by AguilarRaul** [comment]
I'll take care of number 2, as for number 4 I think we already added some comments to the scripts, maybe worth to double check.

**Comment by Lorraine97** [comment]
> I'll take care of number 2, as for number 4 I think we already added some comments to the scripts, maybe worth to double check.

@AguilarRaul do you wanna add a comment to that issue and include the PR with the fix? I will also take another look there.

**Comment by Hongjian-Sam-Li** [comment]
I checked number 4 and the documentations are clear.
